# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('reg_number', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('imei', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('angle_changed', 'Angel changed'), ('position_changed', 'Position changed'), ('main_power_disconnected', 'Main power disconnected'), ('main_power_connected', 'Main power connected'), ('device_armed', 'Device armed'), ('device_disarmed', 'Device disarmed')], default='unknown', max_length=100)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_events', to='smartalarm_api.Tracker')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('alt', models.FloatField(default=0)),
                ('satellites', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('bat_level', models.IntegerField(default=0)),
                ('is_charging', models.BooleanField(default=False)),
                ('car_voltage', models.FloatField(default=0)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_stats', to='smartalarm_api.Tracker')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_asset', to='smartalarm_api.Tracker'),
        ),
    ]
