# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartalarm_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='tracker',
            name='imei',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
