# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartalarm_api', '0002_auto_20170328_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerstat',
            name='car_voltage',
            field=models.FloatField(default=0),
        ),
    ]
