# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartalarm_api', '0003_trackerstat_car_voltage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_end', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_trip_end', to='smartalarm_api.TrackerStat')),
                ('stats_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_trip_start', to='smartalarm_api.TrackerStat')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_trips', to='smartalarm_api.Tracker')),
            ],
        ),
    ]
