# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartalarm_api', '0004_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripstat_stats', to='smartalarm_api.TrackerStat')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='stats_end',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='stats_start',
        ),
        migrations.AddField(
            model_name='trip',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trackerevent',
            name='event_type',
            field=models.CharField(choices=[('angle_changed', 'Angel changed'), ('position_changed', 'Position changed'), ('main_power_disconnected', 'Main power disconnected'), ('main_power_connected', 'Main power connected'), ('device_armed', 'Device armed'), ('device_disarmed', 'Device disarmed'), ('trip_started', 'Trip started'), ('trip_finished', 'Trip finished')], default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tripstat',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripstat_trips', to='smartalarm_api.Trip'),
        ),
    ]
