# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartalarm_api', '0005_auto_20171106_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
