# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartalarm_api', '0007_tripstat_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='address_end',
            field=models.CharField(blank=True, default='unknown', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='address_start',
            field=models.CharField(blank=True, default='unknown', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trackerevent',
            name='event_type',
            field=models.CharField(choices=[('angle_changed', 'Angel changed'), ('position_changed', 'Position changed'), ('main_power_disconnected', 'Main power disconnected'), ('main_power_connected', 'Main power connected'), ('device_armed', 'Device armed'), ('device_disarmed', 'Device disarmed'), ('trip_started', 'Trip started'), ('trip_finished', 'Trip finished'), ('ignition_on', 'Ignition on'), ('ignition_off', 'Ignition off')], default='unknown', max_length=100),
        ),
    ]
