# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-19 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartalarm_api', '0009_tracker_tracker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='tracker_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('owl', 'Owl'), ('coban', 'Coban')], default='unknown', max_length=100),
        ),
    ]
