# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-20 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartalarm_api', '0010_auto_20171119_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_traveled', models.FloatField(default=0)),
                ('count_zero_satellites', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('zone_type', models.IntegerField(blank=True, choices=[(1, 'Circle'), (2, 'Rectangle'), (3, 'Polygon')], null=True)),
                ('bounds', models.CharField(blank=True, max_length=1000, null=True)),
                ('alarm_on', models.IntegerField(blank=True, choices=[(1, 'Zone exit'), (2, 'Zone enter')], null=True)),
                ('alarm_enabled', models.BooleanField(default=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_type',
            field=models.IntegerField(choices=[(1, 'Unknown'), (2, 'Owl'), (3, 'Coban')], default=1),
        ),
        migrations.AddField(
            model_name='zone',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_zones', to='smartalarm_api.Tracker'),
        ),
        migrations.AddField(
            model_name='globalstat',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_globals', to='smartalarm_api.Tracker'),
        ),
    ]
