# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-02 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartalarm_api', '0011_auto_20171120_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackerstat',
            old_name='is_charging',
            new_name='car_running',
        ),
    ]
